name: Go SAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install SAST tools
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run gosec
        run: gosec ./...

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run govulncheck
        run: govulncheck ./...

      - name: Run golangci-lint
        run: golangci-lint run
